# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelib', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Location',
            new_name='location',
        ),
    ]
