# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelib', '0002_auto_20200203_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='Location',
        ),
    ]
