# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-03 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagelib', '0003_auto_20200203_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Location',
            new_name='location',
        ),
    ]
